omarabid/rust-companies

README.md
=> Add brave adblock engine

README.md
Our rust-based reverse proxy handles 500M requests per day and some of that is going to our new app hosting platform that uses the firecracker microVM (another rust project).
=> Add Fly.io

README.md
- [ x ] Company name
- [ x ] Company description
- [ x ] Company location
- [ x ] GitHub link (if available)
- [ x ] Sorted alphabetically
=> Add Red Sift

README.md
=> Update README.md added firo

README.md
Thanks for curating this list. I've added Facebook, Immunant, and Qumulo to the list along with links to their use of Rust.
=> Add Facebook, Immunant, and Qumulo

README.md
=> Add DungeonFog company

README.md
Adding Materialize, the core of which is written in Rust!
=> Add Materialize

README.md
=> README: add Svix to list of companies.

README.md
- [*] Company name
- [*] Company Website
- [*] Company description
- [-] GitHub link (if available)
- [*] Sorted alphabetically
I added it in a new section called News since that's what we do but if you prefer it to go in Technology I'll change it.
=> Add The Daily Edit

README.md
- [*] Company name
- [*] Company Website
- [*] Company description
- [-] GitHub link (if available)
- [*] Sorted alphabetically
=> Add amazon; renamed Facebook to Meta

README.md
- [✔️ ] Company name
- [✔️  ] Company Website
- [ ✔️ ] Company description
- [✔️  ] GitHub link (if available)
- [ ✔️ ] Sorted alphabetically
=> Add Deepgram

README.md
=> Add Aerospace industry and Lechev.space

README.md
=> Add 1Password

README.md
=> Add google

README.md
=> Add Stackable

README.md
=> Added Cryptosat to Aerospace companies

README.md
=> Added HyperSwitch to Fintech

README.md
=> Add corrode Rust consulting

README.md
=> Added Microsoft to the list

README.md
=> Add Tweede golf

README.md
=> Added HuggingFace to Machine Learning | AI

README.md
=> Add Red Iron

README.md
=> Add Espressif Co.

README.md
=> Add Zama and Tailcall

README.md
=> Add FifthTry

README.md
=> Add Vercel

README.md
<hr>
I have additionally fixed typos and updated the link to Google.
I have also created a list of companies where I have seen Rust job openings and would like to synchronize your list with [mine](https://readytotouch.com/organizers/rust/companies). So, I will be adding more companies in the near future.
=> Add SurrealDB

README.md
=> Add Polars

README.md
=> Add TensorZero (Rust-based LLMOps)

README.md
- [ X] Company name
- [X ] Company Website
- [ X] Company description
- [ X] GitHub link (if available)
- [ X] Sorted alphabetically
=> Added LanceDB - multimodal data platform
